### ISSUE TITLE
デザイン面での改善点

### ISSUE THREAD

**Issue by seiya303** [YSP-SINERGY/xserver-sinergy2021-event-website#4]
[状況]
パソコンとスマホで表示されるデザイン面でUX上改善すべき点が見当たった。

[問題点]
UX上気になる部分として残る

[指摘箇所]
- [x] ハンバーガーメニューの位置
- [x] ページタイトルのアイコンが若干横に伸びて写っている
- [x] Twitterの組み込まれたタイムラインの横幅を他のコンポーネントと合わせる
- [x] 青木代表のメッセージを縦に並べる
- [x] スマホで表示した際、発表者を全部閲覧できるようにする。なるべく３人一列、難しければ二人一列
- [x] SINERGYとTeensのフォント調整
- [x] メインページの色彩変更
- [x] 問い合わせフォームの追加
- [x] 支援ボタンの横幅調整
- [x] What's Sinergyの紹介文をイメージからテキストに変える
- [x] コンテナの角を丸から四角に変える
- [x] リンクを別タブで飛ぶようにする
- [x] what's sinergyの説明文に改行や空白行を追加
- [x] youthサイト青木代表メッセージの誤字修正

[受入条件]
上の指摘箇所が全てチェックされた状態

**Comment by seiya303** [comment]
@yuikateraoka 
[こちら](https://github.com/YSP-SINERGY/xserver-sinergy2021-event-website/issues/4#issue-1071074406)で抜けていた部分あれば追加お願いします

**Comment by yuikateraoka** [comment]
メインページの色彩変更以外の修正は完了しました。
上記の件（メインページの色彩）は、どのような色味が良いと思いますか？

**Comment by seiya303** [comment]
@yuikateraoka
個人的にはyoothページの色合い(ダークパープルですかね？)は今のでLGTMですね。

デザイン面についてもう少し検討してみて、こちらのイシューはクローズしたいと思います。

**Comment by seiya303** [comment]
@yuikateraoka 
スラックで追加で指摘を受けた項目を追加しておいたのでご確認お願いします。

**Comment by yuikateraoka** [comment]
@seiya303  
完了です。

**Comment by seiya303** [comment]
デザイン面では現状最適化されていると思うので、こちらのイシューは閉じます。お疲れ様でした。
